[module]
  [module.hugoVersion]
    extended = true
    min = "0.111.1"

[menu]
  [[menu.header]]
    identifier = "home"
    name = "Home"
    weight = 1
    url = ""
  [[menu.header]]
    identifier = "resume"
    name = "Resume"
    weight = 2
    url = "resume"
  [[menu.header]]
    identifier = "posts"
    name = "Posts"
    weight = 3
    url = "posts"
  [[menu.header]]
    identifier = "tags"
    name = "Tags"
    weight = 4
    url = "tags"
  [[menu.header]]
    identifier = "about"
    name = "About"
    weight = 5
    url = "about"

[params]
  fingerprint = "sha256"
  author = "Old Punk"
  homepage = "https://github.com/KyKyPy3"
  license = "MIT"
  licenselink = "https://github.com/KyKyPy3/hugo-theme-codepunk/blob/main/LICENSE"

  # Analytics config
  [params.analytics]
    enable = true

    # Google Analytics
    [params.analytics.google]
      id = "G-2MWWZ25J3X"
      anonymizeIP = true