name = "Codepunk"
license = "MIT"
licenselink = "https://github.com/KyKyPy3/hugo-theme-codepunk/blob/main/LICENSE"
description = "Readable theme for thecodepunk.com homepage"
homepage = "https://github.com/KyKyPy3/hugo-theme-codepunk"
tags = [
  "personal",
  "portfolio",
  "contact",
  "simple",
  "clean",
  "light",
  "dark",
  "blog",
]
features = [
  "blog",
]
min_version = "0.143.1"

[author]
  name = "Efremenko Roman"
  homepage = "https://github.com/KyKyPy3"
